---
driver:
  name: vagrant
provisioner:
  name: chef_solo
  attributes:
    local_ipv4: "10.0.0.3"
    app_restart:
      restart_command: "echo restart"
    rolling_restart:
      restart_command: "rolling_restart"
      ssh:
        user: "deploy"
        public_key: "ssh-rsa IAMAPUBLICKEY"
    opsworks:
      layers:
        rails-puma-app:
          instances:
            app-01:
              private_ip: "10.0.0.1"
              elastic_ip: "54.54.54.54"
            app-02:
              private_ip: "10.0.0.2"
        utility:
          instances:
            util-01:
              private_ip: "10.0.0.3"
            util-02:
              private_ip: "10.0.0.4"

platforms:
  - name: centos-6.6
    driver_config:
      require_chef_omnibus: "11.4 -d /tmp/vagrant-cache/vagrant_omnibus"
suites:
  - name: default
    run_list:
      - recipe[opsworks-rolling-restart]
      - recipe[opsworks-rolling-restart::app_restart]
    attributes:

